obj-$(CONFIG_EMTRION_COMMON)    += emtrion_common.o
obj-$(CONFIG_FB_SH_MOBILE_LCDC) += display.o
obj-$(CONFIG_DIRECTFB_CMDLINE)  += directfb.o
obj-$(CONFIG_SH_EARLY_SD_FIRMWARE) += sd_firmware.o
obj-$(CONFIG_SH_BOOTLOGO)          += bootlogo.o


obj-$(CONFIG_SH_HICO7723)	+= hico7723/
obj-$(CONFIG_SH_DIMM_SH7724)	+= dimm-sh7724/
