# hach-lange support

ccflags-$(CONFIG_DEBUG_HL)  += -DDEBUG


#obj-$(CONFIG_HLIRQ_SUPPORT)        += hl_nmi.o hl_irq.o
#obj-y                              += hl_gen.o
obj-$(CONFIG_FUSIONBOARD_SUPPORT)  += hl_fusion_board.o
#obj-y                              += hl_i2c_akku.o
#obj-y                              += hl_usb_dev/
#obj-y                              += m66291_usb/
obj-$(CONFIG_RL78_SUPPORT)         += RL78_I2C/
