obj-$(CONFIG_EM_BASEBOARD)    += em_baseboard.o
obj-$(CONFIG_EM_COMMON)       += em_common.o
obj-$(CONFIG_EM_COMMON)       += em_module.o
obj-$(CONFIG_EM_DEVICE_SETUP) += em_device_setup.o
obj-$(CONFIG_EM_FIRMWARE_BY_BOOTLOADER) += em_firmware.o
